### ISSUE TITLE
Failure on Linux Python 3.7 `toolchain` build

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scikit-learn-feedstock#77]
The Linux Python 3.7 `toolchain` build is failing on CI with a segmentation fault. Here is [the build]( https://circleci.com/gh/conda-forge/scikit-learn-feedstock/516 ) and [the log](https://github.com/conda-forge/scikit-learn-feedstock/files/2499429/Linux_Python_3.7_Toolchain_Build_Log.txt) for details. We were unable to skip the build using `skip: true` with selectors. So it is left in. Help fixing either of these would be appreciated.

Edit: Have broken out the re-rendering/selector problem as issue ( https://github.com/conda-forge/conda-smithy/issues/917 ). An example of this problem is shown in PR ( https://github.com/conda-forge/scikit-learn-feedstock/pull/78 ).

**Comment by rth** [comment]
Thanks for investigating! @pkgw would you mind opening a new issue with a copy-paste of comment at https://github.com/scikit-learn/scikit-learn/, also with specifying `sklearn.show_versions()` and a link here if possible? Thanks.

 It seems likely due to some of the C code in `scipy.spatial.distance.pdist` failing on read-only mmaps (which is a requirements for us as that happens when using parallel computing with joblib to share data among processes).

**Comment by pkgw** [comment]
@rth Posted as https://github.com/scikit-learn/scikit-learn/issues/12483.

**Comment by pkgw** [comment]
Following up, it seems that this failure represents a genuine scikit-learn bug — see the linked report for discussion.

**Comment by jschueller** [comment]
This one can be closed (#80).
