### ISSUE TITLE
Mac test collection sometimes hangs in Circle

### ISSUE THREAD

**Issue by jnothman** [conda-forge/scikit-learn-feedstock#84]
We managed to get CI to pass in #80 by repeatedly rerunning the failure, but Mac OS runs often seem to timeout at collection.

**Comment by jakirkham** [comment]
Just to add some more detail here.

This failure is the macOS build on Python 2.7 using the new compilers (not the old compilers). So there may be something off about how it was built. Could also be oversubscription of resources given this doesn't always fail. Rebuilding with SSH enabled seems to make the difference when it does work (slightly higher resource limits?).

Should add it looks like we also eventually got it to pass on `master`. So that package is published now.

**Comment by jnothman** [comment]
I am presuming that it's deterministic. Basically, whoever is testing for timeout on the basis of no output (circle?) is only recognising output by a newline character. Without a newline, if the tests take over 10 minutes, it will be killed.

**Comment by jnothman** [comment]
This explains why we have had failure inconsistently on various Mac runs

**Comment by ogrisel** [comment]
Let's close then. However after the merge of the 0.20.2 PR we got the following dependency error on one of the builds: #88.

**Comment by jakirkham** [comment]
We might want to bump up the timeouts once PR ( https://github.com/conda-forge/conda-smithy/pull/973 ) lands in a new `conda-smithy` release.
